### ISSUE TITLE
Mojo::URL syntax error

### ISSUE THREAD

**Issue by zdm** [kraih/mojo#856] opened 2015-10-21 22:00 UTC
line 57:
```
map { /^xn--(.+)$/ ? punycode_decode($_) : $_ } split(/\./, shift, -1))
```
should be:
```
map { /^xn--(.+)$/ ? punycode_decode($1) : $_ } split(/\./, shift, -1))
```
The difference is in the punycode_decode argument.

**Comment by tianon** [comment] 2015-10-21 22:12
How do you figure?  `map` puts the "mapped contents" in `$_`, so the line as-is looks correct to me, and I don't quite see how `$1` could figure in.

**Comment by genio** [comment] 2015-10-21 22:13
```(.+)``` and ```$1```

**Comment by tianon** [comment] 2015-10-21 22:16
Ah right, but `punycode_decode` does handle the `xn--` prefix on lines 137 and 138 (https://github.com/kraih/mojo/blob/b2088ea292b7cbb484a1e91c56fd34cff3008517/lib/Mojo/Util.pm#L137-L138), so this isn't really a syntax error but is perhaps a minor optimization?

**Comment by genio** [comment] 2015-10-21 22:19
I'd be more inclined to get rid of the capturing group here if it's already handled elsewhere:

```/^xn--/ ? punycode_decode($_) : $_```

**Comment by kraih** [comment] 2015-10-21 22:33
Definitely not a syntax error, but a reasonable optimization, thanks.

**Comment by zdm** [comment] 2015-10-21 23:38
This is not just optimization. this is error.
You can try
```
say join '.', map { /^xn--(.+)$/ ? Mojo::Util::punycode_decode($_) : $_ } split( /\./, 'aaa.xn--80aa8ab.com', -1 ); # aaa.ŲŬŲŬxn-.com - invalid result
```
and
```
say join '.', map { /^xn--(.+)$/ ? Mojo::Util::punycode_decode($_) : $_ } split( /\./, 'aaa.xn--80aa8ab.com', -1 ); # aaa.мама.com - OK
```

**Comment by kraih** [comment] 2015-10-21 23:46
@zdm Those examples are literally identical.

**Comment by zdm** [comment] 2015-10-21 23:47
I updated examples, please check.

**Comment by kraih** [comment] 2015-10-21 23:49
@zdm We clearly have a communication problem here, perhaps you could provide a failing test case for `t/mojo/url.t`? https://github.com/kraih/mojo/blob/master/t/mojo/url.t

**Comment by genio** [comment] 2015-10-21 23:51
@zdm  it's moot at this point due to the change that was just submitted, no?

**Comment by zdm** [comment] 2015-10-21 23:56
Guys, I really have no time today. Everything is simple.
Try to decode this domain - aaa.xn--80aa8ab.com. Or any other.

```
use Mojo::Util;

my $domain = 'aaa.xn--80aa8ab.com';

# current code, that work incorrectly
# result is aaa.UUUUxn-.com
say join '.', map { /^xn--(.+)$/ ? Mojo::Util::punycode_decode($_) : $_ } split( /\./, $domain, -1 );

# fixed code
# result is aaa.мама.com
say join '.', map { /^xn--(.+)$/ ? Mojo::Util::punycode_decode($1) : $_ } split( /\./, $domain, -1 );
```

**Comment by genio** [comment] 2015-10-21 23:59
This:
```bash
perl -MData::Dumper -MMojo::URL -E 'my $url = Mojo::URL->new(q(http://aaa.xn--80aa8ab.com/)); say Dumper $url; say $url->ihost'
```

results in:
```bash
$VAR1 = bless( {
                 'host' => 'aaa.xn--80aa8ab.com',
                 'scheme' => 'http',
                 'path' => bless( {
                                    'path' => '/'
                                  }, 'Mojo::Path' )
               }, 'Mojo::URL' );

aaa.xn--80aa8ab.com
```

Whether this is expected behavior or not, I don't know.

**Comment by zdm** [comment] 2015-10-22 00:09
Here is the more clear example:
```
use Mojo::URL;
my $u = Mojo::URL->new('http://aaa.com');
$u->ihost('aaa.xn--80aa8ab.com');
say $u->host;

# result is aaa.ŲŬŲŬxn-.com, but aaa.мама.com is expected
# IDN domain name is decoded incorrectly
```

**Comment by kraih** [comment] 2015-10-22 00:18
Thanks, should be fixed now.

**Closed** 2015-10-22 00:17 UTC
