### ISSUE TITLE
Bug in mojo websocket client with big response

### ISSUE THREAD

**Issue by Logioniz** [kraih/mojo#1106] opened 2017-07-14 06:38 UTC
* Mojolicious version: 7.36
* Perl version: 5.22
* Operating system: Linux

### Steps to reproduce the behavior
If server send big message to client then client generate 1009 error and ioloop generate message.

server
```perl
#!/usr/bin/perl
use Mojo::Base -strict;
use Mojolicious::Lite;
websocket '/' => sub {
  shift->on(text => sub {
    my ($c, $text) = @_;
    $c->send({text => '1' x 1_000_000});
  });
};
app->start;
```
client
```perl
#!/usr/bin/perl
use Mojo::Base -strict;
use Mojo::UserAgent;

Mojo::IOLoop->timer(3 => sub {warn '!!!'});

my $ua = Mojo::UserAgent->new;
$ua->websocket('ws://127.0.0.1:3000/' => sub {
  my ($ua, $tx) = @_;
  say 'WebSocket handshake failed!' and return unless $tx->is_websocket;
  $tx->on(text => sub {
    my ($tx, $text) = @_;
    warn $text;
  });
  $tx->send({text => 'hello'});
});
Mojo::IOLoop->start;
```

### Expected behavior
No warnings

### Actual behavior
Warnings

```
$ perl client.pl 
Use of uninitialized value $loop in hash element at /usr/local/share/perl/5.22.1/Mojo/UserAgent.pm line 200.
Mojo::Reactor::EV: I/O watcher failed: Can't call method "remove" on an undefined value at /usr/local/share/perl/5.22.1/Mojo/UserAgent.pm line 276.
!!!
$
```

**Comment by jberger** [comment] 2017-07-19 14:47
Can confirm. Here it is in the form of a test file:

```perl
use Mojolicious::Lite;

use Test::More;
use Test::Mojo;

my $send = '1' x 1e5;

websocket '/' => sub { shift->send({text => $send}) };

my $t = Test::Mojo->new;

$t->websocket_ok('/')
  ->message_ok
  ->message_is($send)
  ->finish_ok;

done_testing;
```

**Comment by jberger** [comment] 2017-07-19 14:55
Ah, this is just hitting the max websocket size. I was amazed that such a simple behavior could be missed. http://mojolicious.org/perldoc/Mojo/Transaction/WebSocket#max_websocket_size

@kraih is there a warning/log that I'm not seeing when this level is breached? If not perhaps there could be. Anyway, the reported issue is not a bug, so I'm closing it.

**Closed by jberger** 2017-07-19 14:55 UTC

**Comment by kraih** [comment] 2017-07-19 15:07
From [RFC 6455](https://tools.ietf.org/html/rfc6455).
```
1009 indicates that an endpoint is terminating the connection
      because it has received a message that is too big for it to
      process.
```

**Comment by jberger** [comment] 2017-07-19 15:11
Ah yes, well then that is consistent with the HTTP behaviors. I HAD thought that there was a warning to the log but I just looked it up and indeed it is just an error to the client. https://github.com/kraih/mojo/blob/master/lib/Mojo/Message.pm#L169-L179
