### ISSUE TITLE
Inconsistent JSON Boolean conversions

### ISSUE THREAD

**Issue by stuartskelton** [kraih/mojo#972] opened 2016-06-16 07:18 UTC
* Mojolicious version: 6.60
* Perl version: 5.16.3
* Operating system: MacOS 10.10.5, Linux

### Steps to reproduce the behavior

```perl
#!/usr/bin/env perl
use Mojolicious::Lite;

use JSON::XS;
use Cpanel::JSON::XS;
use JSON::PP;
use Mojo::JSON;
use DDP;

my $json = {
    cp   => Cpanel::JSON::XS::true,
    xs   => JSON::XS::true,
    pp   => JSON::PP::true,
    mojo => Mojo::JSON::true,
};

p $json;

get '/' => sub {
    my $c = shift;
    $c->render(
        json => $json
    );
};

app->start;
__DATA__
```

with versions of:
JSON::XS version 99999 required--this is only version 2.34 at -e line 1.
JSON::PP version 99999 required--this is only version 2.27400 at -e line 1
Cpanel::JSON::XS version 9999 required--this is only version 3.0213 at -e line 1.
Mojo::JSON version of 6.60 (same as mojo)

This is Dumped out by DDP,
```
\ {
    cp     JSON::PP::Boolean  {
        public methods (0)
        private methods (1) : __ANON__
        internals: 1
    },
    mojo   JSON::PP::Boolean  {
        public methods (0)
        private methods (1) : __ANON__
        internals: 1
    },
    pp     var{mojo},
    xs     JSON::XS::Boolean  {
        public methods (0)
        private methods (1) : __ANON__
        internals: 1
    }
}
```
This is what is displayed in my browser:

```{"cp":true,"mojo":true,"pp":true,"xs":"1"}```

Update to the latest JSON::XS,
```
\ {
    cp     JSON::PP::Boolean  {
        Parents       Types::Serialiser::BooleanBase
        public methods (0)
        private methods (1) : __ANON__
        internals: 1
    },
    mojo   JSON::PP::Boolean  {
        Parents       Types::Serialiser::BooleanBase
        public methods (0)
        private methods (1) : __ANON__
        internals: 1
    },
    pp     var{mojo},
    xs     var{cp}
}
```

and 
```{"mojo":true,"pp":true,"xs":true}```

I know Cpanel::Json::XS can mess with JSON::XS, however when I remove Cpanel::JSON::XS from this mojolite_app, the same results.

This particular problem is quite evil as JSON, to use JSON::XS, requires 2.34, and falls back to JSON::PP if JSON::XS is at versions 3.0X.

### Expected behavior

A JSON Boolean encoded objects should be converted to their JSON equivalence.
Note:

I have used true in this example. but false is the same 

### Actual behavior

JSON::XS 2.34 Perl Boolean types should be converted correctly into JSON Boolean types.

**Comment by kraih** [comment] 2016-06-16 10:45
Afraid i have to disagree with your expected behaviour. `JSON::XS` being the only module to use a non-standard boolean type is the real bug here, and should be fixed in `JSON::XS`. `JSON::PP::Boolean` has been a core module since Perl 5.14, and has become the de facto standard boolean type for Perl.

**Closed** 2016-06-16 10:45 UTC

**Comment by Grinnz** [comment] 2016-06-16 14:12
Two things to note: The latest version of JSON::XS does get correctly interpreted as a JSON::PP::Boolean, and it is suggested to use JSON::MaybeXS which prefers Cpanel::JSON::XS and has much less overhead than JSON.

**Comment by stuartskelton** [comment] 2016-06-16 15:45
Ok and thank you for looking at this.  

This feature came up when we were using JSON::XS (via JSON)  on the back end and using render(Json) on the front end, and it was converting JSON::XS::False to  "0" which it is not false in JSON.

I cannot be the only person who has bumped into this, but if its here hopefully someone will find it, and plan to do the same as me, and move away from 'use JSON' altogether.

**Comment by Grinnz** [comment] 2016-06-16 16:11
You may also consider using https://metacpan.org/pod/Mojo::JSON::MaybeXS so that mojo can use JSON::MaybeXS for rendering as well.
