### ISSUE TITLE
Mojo::Content::MultiPart is very slow to reconsruct body contents

### ISSUE THREAD

**Issue by philipspencer** [kraih/mojo#1206] opened 2018-04-01 01:37 UTC
* Mojolicious version: 7.71
* Perl version: 5.24.3
* Operating system: Fedora 27 Linux

When a Mojolicious request is of content type multipart/form-data it takes an inordinately long time (~ 10 seconds for a form with ~2000 parts / parameters) for a call to build_body to reconstruct the body.

This is because build_body calls Mojo::Content::Multipart::get_body_chunk to get each chunk, but get_body_chunk has no state memory so each call starts at the very first part and loops over all parts, counting their lengths, until the accumulated length reaches the offset it's looking for. Then the next call, to fetch the next part, restarts at the very beginning and repeats all this work.

In practice this causes a problem when using the CGI plugin to farm a request off to an external script. If input is a 2000-parameter form submission, it takes about 10 seconds from the time "routing to a callback" is logged until the extrernal script is given control, and all of this time is spent in the second of the following two lines of Plugin::CGI's code:

    $stdin = Mojo::Asset::File->new;
    $stdin->add_chunk($c->req->build_body);

(Why it is doing this instead of just calling $c->req->body I don't know, but it does.)

If we apply the following patch to Mojo::Content::MultiPart.pm, remembering which parts were skipped and how long the skipped parts were, so that a subsequent call to get_body_chunk with a larger offset will automatically skip the same parts too, then we experience a speed improvement of more than ten-fold -- nearly a hundredfold in some caes, taking only a fraction of a second to do what was taking 10+ seconds without the patch.

However, I'm not sure it's the best approach or whether some more major refactoring of the code would be better.

```
diff --git a/lib/Mojo/Content/MultiPart.pm b/lib/Mojo/Content/MultiPart.pm
index e250829..3d2c021 100644
--- a/lib/Mojo/Content/MultiPart.pm
+++ b/lib/Mojo/Content/MultiPart.pm
@@ -69,7 +69,12 @@ sub get_body_chunk {
 
   # Prepare content part by part
   my $parts = $self->parts;
-  for (my $i = 0; $i < @$parts; $i++) {
+  my $i_start = 0;
+  if ($self->{last_offset} && $offset > $self->{last_offset}) {
+     $i_start = 1 + $self->{last_skipped_part};
+     $len = $self->{last_skipped_len};
+  }
+  for (my $i = $i_start; $i < @$parts; $i++) {
     my $part = $parts->[$i];
 
     # Headers
@@ -92,6 +97,9 @@ sub get_body_chunk {
     return substr "\x0d\x0a--$boundary\x0d\x0a", $offset - $len
       if ($len + $boundary_len) > $offset;
     $len += $boundary_len;
+    $self->{last_offset} = $offset;
+    $self->{last_skipped_part} = $i;
+    $self->{last_skipped_len} = $len;
   }
 }
```

**Comment by kraih** [comment] 2018-04-01 14:04
I'm not sure what this issue is supposed to achieve. At first it looks like a bug report against `::Plugin::CGI`, but this would be the wrong place for that. But `Mojo::Content::MultiPart::get_body_chunk` being slow might have a negative effect on `Mojo::UserAgent` too. In which case we should do some sort of caching to improve its performance. But until there's a reproducible benchmark i don't think there is anything we can do.

**Comment by philipspencer** [comment] 2018-04-01 17:48
Okay, here's a fairly minimal reproducer.

```
$ cat > slowmojo
use Mojolicious::Lite;
use Time::HiRes;

post '/test' => sub {
   my $c = shift;
   my $start_time = Time::HiRes::time;
   my $body = $c->req->build_body;
   $c->render(text => "Rebuilt body: " .  length($body) . " bytes in " .
	1000*(Time::HiRes::time - $start_time) . " milliseconds\n");
};

app->start;
```

```
$ morbo slowmojo
Server available at http://127.0.0.1:3000
````
```
$  perl -we 'system "curl", (map {("--form", "foo$_=$_") } (0..2000)), "http://localhost:3000/test";'
Rebuilt body: 197926 bytes in 21859.3811988831 milliseconds
```
With the above patch:
```
 perl -we 'system "curl", (map {("--form", "foo$_=$_") } (0..2000)), "http://localhost:3000/test";'
Rebuilt body: 197926 bytes in 134.493112564087 milliseconds
```
Time taken is reduced from over 20 seconds down to 134 milliseconds.

**Comment by kraih** [comment] 2018-04-01 22:24
@philipspencer That is not something we expect to be efficient i'm afraid and does not qualify. Rebuilding the request body is merely there for debugging purposed.

**Comment by kraih** [comment] 2018-04-01 22:30
File uploads with `Mojo::UserAgent` are a likely candidate for a valid use case that needs optimization.

**Comment by kraih** [comment] 2018-04-01 23:18
A synthetic `Mojo::UserAgent` benchmark could look like this:
```
$ perl -Mojo -E 'my $t = app->ua->transactor; my $m = []; push @$m, "a" x 1000000 for 1 .. 100; n { $t->tx(GET => "mojolicious.org" => multipart => $m)->req->to_string } 10'
3.0384 wallclock secs ( 2.43 usr +  0.60 sys =  3.03 CPU) @  3.30/s (n=10)

$ perl -Ilib -Mojo -E 'my $t = app->ua->transactor; my $m = []; push @$m, "a" x 1000000 for 1 .. 100; n { $t->tx(GET => "mojolicious.org" => multipart => $m)->req->to_string } 10'
2.19746 wallclock secs ( 1.58 usr +  0.61 sys =  2.19 CPU) @  4.57/s (n=10)
```

**Comment by kraih** [comment] 2018-04-01 23:26
And another, better one, uploading 100 1MB files:
```
perl -Mojo -E 'f("/Users/sri/test.txt")->spurt("a" x 1000000)'

$ perl -Mojo -E 'my $t = app->ua->transactor; my $m = []; push @$m, {file => "/Users/sri/Downloads/test.txt"} for 1 .. 100; n { $t->tx(GET => "mojolicious.org" => multipart => $m)->req->to_string } 100'

$ perl -Ilib -Mojo -E 'my $t = app->ua->transactor; my $m = []; push @$m, {file => "/Users/sri/test.txt"} for 1 .. 100; n { $t->tx(GET => "mojolicious.org" => multipart => $m)->req->to_string } 100'
0.509484 wallclock secs ( 0.41 usr +  0.09 sys =  0.50 CPU) @ 200.00/s (n=100)
```

**Comment by kraih** [comment] 2018-04-01 23:44
I've committed a shortened version of this for now. https://github.com/kraih/mojo/commit/2b6078216eee54e4237488e7be7ab79107d219f2 But i'm not entirely sure yet if it should stay. That will ultimately depend on if we can find a more realistic benchmark.

**Comment by philipspencer** [comment] 2018-04-02 03:46
Many thanks!

Multipart encoding is fairly standard on forms even if they don't have file uploads (or maybe have one file upload field and many other regular parameters). And it is not unusual for a form to have hundreds or thousands of parameters (e.g. we have a legacy form, not yet using AJAX/PJAX, for managing a conference: 100 participants, 30 tallks, a dozen tweakable data points for each = 1560 parameters in the form).

So while it may not be realistic to have a form with 100 file upload fields, it most certainly *is* realistic to have a multipart-encoded form with several hundred parameters, say param1=1 through param*n*=*n*.

Here is a modification of your benchmark to test that.

### Unpatched Results

Note that, while 100 parameters in the form is still reasonable, the time rises cubicly as you move to 200, 300, or 400 parameters, and at this rate of increase a 1000-part form body would take a full hour to build!

```
$ perl  -Mojo -E 'my $t = app->ua->transactor; my $m=[]; push @$m, { content=>"param$_=$_" } for 1 .. 100; n { $t->tx(GET => "mojolicious.org" => multipart => $m)->req->to_string } 100'
3.92783 wallclock secs ( 3.90 usr +  0.00 sys =  3.90 CPU) @ 25.64/s (n=100)
```
```
$ perl -Mojo -E 'my $t = app->ua->transactor; my $m=[]; push @$m, { content=>"param$_=$_" } for 1 .. 200; n { $t->tx(GET => "mojolicious.org" => multipart => $m)->req->to_string } 200'
28.8515 wallclock secs (28.67 usr +  0.00 sys = 28.67 CPU) @  6.98/s (n=200)
```
```
$  perl -Mojo -E 'my $t = app->ua->transactor; my $m=[]; push @$m, { content=>"param$_=$_" } for 1 .. 300; n { $t->tx(GET => "mojolicious.org" => multipart => $m)->req->to_string } 300'
97.087 wallclock secs (96.56 usr +  0.01 sys = 96.57 CPU) @  3.11/s (n=300)
```
```
$  perl -Mojo -E 'my $t = app->ua->transactor; my $m=[]; push @$m, { content=>"param$_=$_" } for 1 .. 400; n { $t->tx(GET => "mojolicious.org" => multipart => $m)->req->to_string } 400'
221.593 wallclock secs (219.79 usr +  0.23 sys = 220.02 CPU) @  1.82/s (n=400)
```

### Patched results

The patch transforms build_body from quadratic to linear behaviour, and the overall behaviour of this benchmark changes from cubic to quadratic:

```
 $ perl  -Ilib -Mojo -E 'my $t = app->ua->transactor; my $m=[]; push @$m, { content=>"param$_=$_" } for 1 .. 100; n { $t->tx(GET => "mojolicious.org" => multipart => $m)->req->to_string } 100'
0.588792 wallclock secs ( 0.58 usr +  0.00 sys =  0.58 CPU) @ 172.41/s (n=100)
```
```
$  perl  -Ilib -Mojo -E 'my $t = app->ua->transactor; my $m=[]; push @$m, { content=>"param$_=$_" } for 1 .. 200; n { $t->tx(GET => "mojolicious.org" => multipart => $m)->req->to_string } 200'
2.27812 wallclock secs ( 2.26 usr +  0.00 sys =  2.26 CPU) @ 88.50/s (n=200)
```
```
$  perl  -Ilib -Mojo -E 'my $t = app->ua->transactor; my $m=[]; push @$m, { content=>"param$_=$_" } for 1 .. 300; n { $t->tx(GET => "mojolicious.org" => multipart => $m)->req->to_string } 300'
5.20263 wallclock secs ( 5.16 usr +  0.00 sys =  5.16 CPU) @ 58.14/s (n=300)
```
```
perl  -Ilib -Mojo -E 'my $t = app->ua->transactor; my $m=[]; push @$m, { content=>"param$_=$_" } for 1 .. 400; n { $t->tx(GET => "mojolicious.org" => multipart => $m)->req->to_string } 400'
9.2013 wallclock secs ( 9.14 usr +  0.00 sys =  9.14 CPU) @ 43.76/s (n=400)
```
Presumably a similar patch could be applied to some other piece of code in the chain to transform it from quadratic to linear too, and then the whole process of building a multipart form would scale linearly in the number of parts, which would be highly desirable.

Finally, I do want to repeat that my initial reproducer, even though doing something that "is intended only for debugging and not meant to be efficient", is *exactly* what the CGI plugin is using to add the ability to fork a legacy CGI program from Mojolicious, so this is a showstopper to anyone wanting to move a legacy CGI program into the Mojolicious umbrella in preparation for refactoring into a modern Ajax app.

Presumably I should file a bug report with that plugin's maintainer(s), to have them get the request body some other way. I did test, though, and it appears not to be as easy as calling req->body; the process just hangs if I try that (probably something to do with how they've forked to detach from the main IO loop).  I will try looking through the CGI plugin code to see why it hangs when I call req->body instead of req->build_body, but if you have any pointers that I can suggest to them when filing the bug report I'd greatly appreciate it.

**Comment by kraih** [comment] 2018-04-02 13:32
Looks like the optimization is worth keeping for `Mojo::UserAgent` alone. `Mojolicious::Plugin::CGI` getting faster is a nice bonus though.

**Closed by kraih** 2018-04-02 13:32 UTC
Labels: needs more information
